### ISSUE TITLE
Support a nested map that includes xUnit class names

### ISSUE THREAD

**Issue by iamEAP** [tableau-mkt/testrail-cli#4]
In `.testrail-cli.yml`, we should support a mapping like this:

```yaml
# Proposed:
caseClassAndNameToIdMap:
  "Class Name for Test Case as reported by xUnit":
    "Test Name associated with above class": 123 # TestRail Case ID

# Existing:
caseNameToIdMap:
  "Test Name for Test Case as reported by xUnit": 234 # TestRail Case ID 
```

...In cases where test names may be repeated across several classes.
